# File: .github/workflows/cd-pipeline.yml

name: CD Pipeline on Self-Hosted Runner

on:
  push:
    branches:
      - main  # or your deployment branch
    paths:
      - 'CD-Pipeline-Github-Actions/**'  # only run when this directory is changed

jobs:
  deploy:
    name: Deploy with Self-Hosted Runner
    runs-on: self-hosted  # key part: this uses your self-hosted runner

    defaults:
      run:
        working-directory: CD-Pipeline-Github-Actions  # relative to root of repo

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # change to your needed version

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run App or Tests
        run: python app.py  # or your own command

