# File: .github/workflows/cd-pipeline.yml

name: CD Pipeline on Self-Hosted Runner

on:
  push:
    branches:
      - main  # or your deployment branch
    paths:
      - 'CD-Pipeline-Github-Actions/**'  # only run when this directory is changed

jobs:
  deploy-to-dev:
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
    steps:
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y wget
        wget -qO "/usr/local/bin/kubectl" https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl
        chmod +x "/usr/local/bin/kubectl"
        kubectl config set-cluster kind-actions-kind --server=https://host.docker.internal:6444/ --insecure-skip-tls-verify=true
        kubectl config set-credentials actions-dev --token="eyJhbGciOiJSUzI1NiIsImtpZCI6IkZaYjJXbFgwRndGSzBEa2dVc2dQeUlrNWtsMEI4QWlxTUhoakp4ZGZibjgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzUyNjg3NjEyLCJpYXQiOjE3NTI2ODQwMTIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiNjY5MzczNmUtODc0Zi00MzRlLThjOTEtNzZmN2Y4MWJjMjQ3Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZXYiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiYWN0aW9ucy1kZXYiLCJ1aWQiOiI5NjY4ZDRmOC02MGIyLTRlN2QtODBhYS0zOWNhOTA0Y2Q4NWIifX0sIm5iZiI6MTc1MjY4NDAxMiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRldjphY3Rpb25zLWRldiJ9.eksM1wgc8EQsxXeq33NwgNnpqGpFRnnyKyTc0EaAFb9oHFL0jPTz7fBhvDypNT2jdFor_B1LmWOA0j8H0IVR_p-G1hLUmNvg4UHTQ0J-tmusDT0zrlFhKfs0kb0nWmNwpBxkATHHPCuHRj0EenNoCBeValnr8Ww0RLJVP4LuvCmN1DvxHzUB2BxIN1RkZlPxBxqp5wNLFHmoGdXk3admcqmn_zIxaBWHXvqNpPmBO9_7_kFiMffGqdStcA0zCAYpbT1G5ekbzHS4px8rFGbn7pbUNhjpa4Kr0muulpl_jR2ozm0HlE1F1_LyjfihjfKASrSUZp6DsP9mVFmYziE4_w"
        kubectl config set-context actions-dev --user=actions-dev --cluster=kind-actions-kind --namespace=dev
        kubectl config use-context actions-dev
    - name: Deploy to dev namespace
      run: |
        kubectl create deploy flask-ping-server --image=\${{ secrets.DOCKERHUB_USERNAME }}/flask-ping-server:latest --replicas=2 --port=5000 --dry-run=client -o yaml > flask-ping-server.yaml
        kubectl replace --force -f flask-ping-server.yaml
    
