name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: self-hosted
    container:
      image: python:3.12-rc-bullseye
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Install pip requirements
      run: |
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        python3 -m pytest -v
  image-build:
    runs-on: self-hosted
    needs: [unit-tests]
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: \${{ secrets.DOCKERHUB_USERNAME }}
        password: \${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: \${{ secrets.DOCKERHUB_USERNAME }}/flask-ping-server:latest
