# File: .github/workflows/cd-pipeline.yml

name: CD Pipeline on Self-Hosted Runner

on:
  push:
    branches:
      - main  # or your deployment branch
    paths:
      - 'CD-Pipeline-Github-Actions/**'  # only run when this directory is changed

jobs:
  unit-tests:
      runs-on: self-hosted
      defaults:
        run:
          working-directory: CD-Pipeline-Github-Actions  
      container:
        image: python:3.12-rc-bullseye
      
      steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Install pip requirements
        run: |
          pip install -r requirements.txt
      
      - name: Run unit tests
        run: |
          python3 -m pytest -v
  deploy-to-dev:
    runs-on: self-hosted
    # needs: [image-build]
    steps:
    - name: set configuration
      run: |
        kubectl config set-cluster kind-actions-kind --server=https://0.0.0.0:6443/ --insecure-skip-tls-verify=true
        kubectl config set-credentials actions-dev --token="\${{ secrets.ACTIONS_DEV_TOKEN }}"
        kubectl config set-context actions-dev --user=actions-dev --cluster=kind-actions-kind --namespace=dev
        kubectl config use-context actions-dev
    - name: Deploy to dev namespace
      run: |
        kubectl create deploy flask-ping-server --image=\${{ secrets.DOCKERHUB_USERNAME }}/flask-ping-server:latest --replicas=2 --port=5000 --dry-run=client -o yaml > flask-ping-server.yaml
        kubectl replace --force -f flask-ping-server.yaml
    
